#!/usr/local/bin/python3.7

import boto3
import datetime
import time
import random
import copy
import os
import re

def atoi(text):
    return int(text) if text.isdigit() else text

def natural_keys(text):
    return [ atoi(c) for c in re.split(r'(\d+)', text) ]


today = datetime.date.today()
today_string = time.strftime('%Y-%m-%d.%H%M%S')

print (today_string)

ec2_client = boto3.client('ec2','us-east-1')
ec2_autoscale = boto3.client('autoscaling','us-east-1')
ec2_resource = boto3.resource('ec2','us-east-1')


instances = ec2_resource.instances.filter(
        Filters = [ {'Name' : 'tag:Name', 'Values' : [ 'ec2-name*' ]},
                    {'Name' : 'instance-state-name', 'Values' : [ 'running' ]}
         ]
    )

ec2_list = []

for instance in instances:
    ec2_list.append(instance.id)
print (ec2_list)

gateway = random.choice(ec2_list)
print (gateway)

image = ec2_client.create_image(
    InstanceId={ec2_name},
    Name="{ec2_name} " + today_string,
    Description="{ec2_name} " + today_string,
    NoReboot=True,
    DryRun=False)

image_resource = ec2_resource.Image(
                                image['ImageId'])

image_resource.create_tags(Tags=[ { 'Key': 'Name', 'Value': '{ec2_name} ' + today_string },
                                  { 'Key': 'env', 'Value': 'production' },
                                  { 'Key': 'Use', 'Value': '' }                                
                                ])

time.sleep( 30 )

block_devices = copy.deepcopy(image_resource.block_device_mappings)
print (block_devices)

for snap in block_devices:
    if not 'Ebs' in snap:
        continue
    snapshot_id = snap['Ebs']['SnapshotId']
    print (snapshot_id)
    snapshot = ec2_resource.Snapshot(snapshot_id)
    print (snapshot)
    
    ec2_client.create_tags(Resources=[snapshot_id,],Tags=[ { 'Key': 'Name', 'Value': '{ec2_name} ' + today_string },
                                  { 'Key': 'env', 'Value': 'production' },                        
                                  { 'Key': 'Use', 'Value': '' }                                
                                ])


ami_image_id = list(map(lambda i: i['ImageId'], ec2_client.describe_images(
    Filters = [ {'Name' : 'tag:Name', 'Values' : [ '{ec2_name} ' + today_string ]},
  ] 
    )['Images']))

ec2_ami_image_id = (' ' .join(ami_image_id))

print (ec2_ami_image_id)

describe_templates = ec2_client.describe_launch_templates(
    LaunchTemplateNames=[
        '{ec2_launch_template_name}',
    ],
)

print (describe_templates)


launch_template_id = describe_templates.get('LaunchTemplates')[0]['LaunchTemplateId']

version_description = ('{ec2_launch_tmeplate_name} ' + today_string)


update_launch_template = ec2_client.create_launch_template_version(
    LaunchTemplateId=launch_template_id,
    SourceVersion="$Latest",
    VersionDescription=version_description,
            LaunchTemplateData={
                "ImageId": ec2_ami_image_id
            }
        )

print (update_launch_template)

current_version_number = describe_templates.get('LaunchTemplates')[0]['LatestVersionNumber']

print (current_version_number)

modify_launch_template = ec2_client.modify_launch_template(
            LaunchTemplateId=launch_template_id,
            DefaultVersion="$Latest"
        )
        
print (modify_launch_template)


ami_image_name = list(map(lambda i: i['Name'], ec2_client.describe_images(
    Filters = [ {'Name' : 'tag:Name', 'Values' : [ '{ec2_name}*' ]},
  ] 
    )['Images']))

ec2_ami_image_name = (' ' .join(ami_image_name))

ami_image_list = []

for ami in ami_image_name:
    ami_image_list.append(ami)
print (ami_image_list)

ami_image_list.sort(key=natural_keys)


if len(ami_image_list) > 3:
    result = [ ami_image_list[0] ]
    result_image = (' ' .join(result))
    print (result_image)

    result_ami_name = list(map(lambda i: i['ImageId'], ec2_client.describe_images(
        Filters=[
                 {
                   'Name' : 'tag:Name',
                   'Values' : [ result_image ]
                 },
       ] 
    )['Images']))
    
    ec2_ami_purge = (' ' .join(result_ami_name))
    
    print (ec2_ami_purge)

    result_launch_template_version = ec2_client.describe_launch_template_versions(
        DryRun=False,
        LaunchTemplateId=launch_template_id,
        Filters=[
                 {
                    'Name': 'image-id',
                    'Values': [ec2_ami_purge]
                 }
        ]
    )

    print (result_launch_template_version)
    
    ec2_launch_template_version = result_launch_template_version.get('LaunchTemplateVersions')[0]['VersionNumber']
    
    print (ec2_launch_template_version)
    
    ec2_purge_old_launch_template_version = ec2_client.delete_launch_template_versions(
       DryRun=False,
       LaunchTemplateId=launch_template_id,
       Versions=[
                  str(ec2_launch_template_version)
     ] 
   )
    
    print (ec2_purge_old_launch_template_version)
    
    
    ec2_deregister_ami = ec2_client.deregister_image(
       ImageId=ec2_ami_purge,
       DryRun=False
   )
    
    print (ec2_deregister_ami)
    
    ec2_ami_snapshots = ec2_client.describe_snapshots(Filters=[{'Name': 'tag:Name', 'Values': [ result_image ]}])
    
    
    for snapshot in ec2_ami_snapshots['Snapshots']:
            delete_snapshots = (snapshot['SnapshotId'])
            print (delete_snapshots)
            
            delete = ec2_client.delete_snapshot(
                                                   SnapshotId=delete_snapshots,
                                                   DryRun=False)
            
            print (delete)

time.sleep( 60 )

autoscale_refresh = ec2_autoscale.start_instance_refresh(
        AutoScalingGroupName='{ec2_autoscale_group_name}',
        Strategy='Rolling',
        Preferences={
            'MinHealthyPercentage': 80,
            'CheckpointPercentages': [20,100],
            'CheckpointDelay': 100
        }
    )
    
    
print (autoscale_refresh)
